logLevel: "error"

db:
    username: "user"
    password: "1234"
    host: "localhost"
    port: "3306"
    dbname: "ticks"
    sslmode: "disable"

service:
    batchSize: 10

coinBaseClient:
    url: "wss://ws-feed.exchange.coinbase.com"